# Checking if network exists
check_network:
	if [ -z "$$(sudo docker network ls -q -f name=my_network)" ]; then \
		echo "Network my_network does not exist. Creating..."; \
		sudo docker network create my_network; \
	else \
		echo "Network my_network already exists."; \
	fi


# Building and running the containers
run: check_network
	sudo docker build -t my-server-app ./Server
	sudo docker build -t loadbalancer ./loadBalancer
	sudo docker run -p 5000:5000 --privileged=true -v /var/run/docker.sock:/var/run/docker.sock --name my_loadbalancer_app --network my_network -it loadbalancer

# Building and running the containers using docker-compose
run_compose: check_network
	sudo docker-compose build
	sudo docker-compose up load_balancer

# 
run_DB_Server_Test: check_network
	sudo docker build -t database ./database
	sudo docker run -p 3307:3306 --network my-network --name DB database
	sudo docker build -t my-server-app ./Server
	sudo docker run -p 5000:5000 -e "SERVER_ID=123456" -e "MYSQL_USER=root" -e "MYSQL_DATABASE=StudT" -e "MYSQL_PORT=3306" -e "MYSQL_HOST=DB" -e "MYSQL_PASSWORD=your_mysql_password" --network my-network  --name server1 my-server-app
	sudo docker build -t test ./Test
	sudo docker run --network my-network test